### ISSUE TITLE
访问网站时导致证书验证失败，并且访问其他网站会跳转到LuCL界面

### ISSUE THREAD

**Issue by InsOnYou** [SuLingGG/OpenWrt-Mini#1]
设备：树莓派4B
![批注 2021-02-28 180315](https://user-images.githubusercontent.com/29951150/109414709-3e0b3a80-79ef-11eb-8226-8baa7c5c79ab.png)

**Comment by SuLingGG** [comment]
没遇到过...
有几个思路就是，

1. 善用 Chrome 的 Network 调试。
2. 尝试 dig 或者 ping 查看 DNS 解析以及主机响应。
3. 尝试点击小锁头查看证书来源。
4. 尝试看一下本机的 DNS 解析是否正确。
5. 更换浏览器或者访问设备是否能解决问题。

本项目只提供极其有限的支持，如果要反馈问题麻烦提供尽可能全甚至繁琐的信息。
光一个 "树莓派 4 " 这点信息是解决不了什么问题的...
