### ISSUE TITLE
请问大佬这个支持docker安装吗？

### ISSUE THREAD

**Issue by CodeDreamfy** [SuLingGG/OpenWrt-Mini#10]
我想把这个固件作为旁路由在docker里面跑，之前按照您的教程把旁路由实现了，但是插件比较多，也想要精简点~

**Comment by SuLingGG** [comment]
不支持的。
Docker 版的插件配置已经是最优解了，基本不会出现插件之间互相冲突的情况，并且占用也不大，实在没有必要精简插件。

**Comment by CodeDreamfy** [comment]
> 不支持的。
> Docker 版的插件配置已经是最优解了，基本不会出现插件之间互相冲突的情况，并且占用也不大，实在没有必要精简插件。

好的，感谢~
