### ISSUE TITLE
R2S 的 4/30 mini 固件，安裝 passwall 時報錯

### ISSUE THREAD

**Issue by TomFoxLee** [SuLingGG/OpenWrt-Mini#17]
SuLing 大佬，我在 TG 群有發訊息，不過這邊也學習發一下 PR... ^^||

早些時候以升級方式安裝了 4/30 的 R2S mini 固件，不過發現 passwall 無法安裝，出現以下錯誤：

$ opkg install luci-app-passwall
Unknown package 'luci-app-passwall'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.

在這邊匯報一下，看看大佬您下次更動的時候能不能順便修正一下。
非常感謝！

**Comment by TomFoxLee** [comment]
目前的固件已經可以安裝了。感謝 SuLingGG 大佬！

**Comment by bmyjacks** [comment]
R4S的也ok
