### ISSUE TITLE
软件源失效

### ISSUE THREAD

**Issue by swim3811** [SuLingGG/OpenWrt-Mini#19]
Collected errors:
 * opkg_download: Failed to download http://openwrt.cc/snapshots/packages/aarch64_generic/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://openwrt.cc/snapshots/packages/aarch64_generic/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://openwrt.cc/snapshots/packages/aarch64_generic/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://openwrt.cc/snapshots/packages/aarch64_generic/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://openwrt.cc/snapshots/packages/aarch64_generic/telephony/Packages.gz, wget returned 8.

**Comment by SuLingGG** [comment]
IDC 那边出问题了，无解。
