### ISSUE TITLE
Docker容器启动失败

### ISSUE THREAD

**Issue by kkkevin07** [SuLingGG/OpenWrt-Mini#2]
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:352: getting the final child's pid from pipe caused: EOF: unknown

**Comment by SuLingGG** [comment]
这是已知问题，暂时无法解决。

**Comment by SuLingGG** [comment]
已修复。需要重刷/升级固件，重新安装 docker 或 luci-app-dockerman 才能解决。
