### ISSUE TITLE
luci-app-oaf 以及luci-app-appfilter不显示选择用户

### ISSUE THREAD

**Issue by aenron** [SuLingGG/OpenWrt-Mini#22]
作者基于lean的lede源码开发适配的，openwrt主干还没适配完，所以openwrt主干版本使用会有些BUG。有挺多人在作者issues提出不显示选择用户这个问题，作者给出的建议是先采用稳定分支oaf-3.0.1。所以大佬能否先使用oaf-3.0.1分支的luci-app-oaf？等后续稳定后，再考虑切换到luci-app-oaf 的master分支。

**Comment by SuLingGG** [comment]
已于 0e20176f0d00b4b5e03b8823a468b6db9c93ec3c 切换至 oaf-3.0.1 分支。

**Comment by aenron** [comment]
感谢
