### ISSUE TITLE
希望可以新增软件包 luci-app-bypass

### ISSUE THREAD

**Issue by r6c** [SuLingGG/OpenWrt-Mini#3]
该插件集成了dns解决方案

源码地址为

https://github.com/garypang13/luci-app-bypass

**Comment by SuLingGG** [comment]
添加了 luci-app-bypass 和 luci-app-dnsfilter，按设备编译顺序最迟后天生效。
如果你的设备在今天进行了编译，那么今天编译的设备已生效。
