### ISSUE TITLE
软件包安装失败

### ISSUE THREAD

**Issue by zhiwen95** [SuLingGG/OpenWrt-Mini#31]
执行 `opkg install luci-app-ssr-plus` 每次都有不同的错误
<img width="1040" alt="Snipaste_2021-07-25_13-41-50" src="https://user-images.githubusercontent.com/14962143/126889031-6a8f3f99-023a-4af7-9585-608f1ff9dcb4.png">

**Comment by tenkawataiyo** [comment]
我也遇到了，树莓派4B，今天的固件，passwall等都安装不上
![image](https://user-images.githubusercontent.com/76888661/126890904-5cb625cf-1b43-46d7-bf20-34a73bfa18d9.png)

**Comment by SuLingGG** [comment]
@zhiwen95 @tenkawataiyo 有一个节点坏了，导致其他后端节点数据不同步，现在已经切为单节点运行了，opkg update 然后再安装需要的软件包试试看。

**Comment by zhiwen95** [comment]
今天正常
