### ISSUE TITLE
怎么安装docker

### ISSUE THREAD

**Issue by Pc6** [SuLingGG/OpenWrt-Mini#35]
你好，请问这个固件要怎么安装docker呢？我的设备是树莓派4b，没有搜到opkg包，是需要编译集成进去吗？

**Comment by zzcabc** [comment]
@Pc6 先opkg update，然后opkg install luci-app-dockerman luci-i18n-dockerman-zh-cn，此过程需要联网

**Comment by Pc6** [comment]
@zzcabc 感谢
