### ISSUE TITLE
竞斗云的USB无法使用。

### ISSUE THREAD

**Issue by yuanxiang2015** [SuLingGG/OpenWrt-Mini#37]
日志全是这条：
Thu Aug 19 23:53:24 2021 kern.err kernel: [1087777.297624] usb usb2-port1: Cannot enable. Maybe the USB cable is bad?

**Comment by SuLingGG** [comment]
这是正常日志：
![Snipaste_2021-09-05_13-34-11](https://user-images.githubusercontent.com/22287562/132116607-ff079331-c3c9-4eef-b349-52787b9dc262.png)
![Snipaste_2021-09-05_13-34-27](https://user-images.githubusercontent.com/22287562/132116609-15c302a9-54fd-4c63-8f96-5183cbba6403.png)
可能你的 USB 接口有物理损坏。
