### ISSUE TITLE
今日更新的orangepi zero固件无法启动，不知道啥原因。

### ISSUE THREAD

**Issue by aizhouyi** [SuLingGG/OpenWrt-Mini#4]
今日更新的orangepi zero固件无法启动，不知道啥原因。

**Comment by SuLingGG** [comment]
我这边没有更改别的设置，建议按
https://openwrt.cc/restore/
的方法试一下，如果还是不行我这边也没有什么更好的办法了。
因为本项目支持的设备很多，所以我这边也没有办法一一测试。

**Comment by aizhouyi** [comment]
好的，我去试下看看，或者我等待看下接下来几次的更新情况。
