### ISSUE TITLE
树莓派4B可以考虑编译进去 kmod-r8168 吗？

### ISSUE THREAD

**Issue by JunyuMu** [SuLingGG/OpenWrt-Mini#40]
看到配置里面
```
CONFIG_PACKAGE_kmod-r8168=n
```

**Comment by SuLingGG** [comment]
之前编译进去会出错，所以取消掉了。

**Comment by JunyuMu** [comment]
我昨天按照这个项目在自己电脑上编译了一下。
config里面，我只改了 `CONFIG_PACKAGE_kmod-r8168=y`
```
make package/install || make package/install -j1 V=s  //这个会报错
make target/install || make target/install -j1 V=s // 这个没有
```
[代码](https://github.com/SuLingGG/OpenWrt-Mini/blob/main/.github/workflows/build-rpi4-openwrt.yml#L233-L234)
最后生成的img没啥问题，能正常跑。
