### ISSUE TITLE
无法安装docker

### ISSUE THREAD

**Issue by fucktimi** [SuLingGG/OpenWrt-Mini#43]
提示如下：

Unknown package 'luci-app-dockerman'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency docker for luci-app-dockerman
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-dockerman found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-dockerman.

好像是软件库里没有docker这个依赖。

**Comment by SuLingGG** [comment]
> 提示如下：
> 
> Unknown package 'luci-app-dockerman'. Collected errors:
> 
> * pkg_hash_check_unresolved: cannot find dependency docker for luci-app-dockerman
> * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-dockerman found, but incompatible with the architectures configured
> * opkg_install_cmd: Cannot install package luci-app-dockerman.
> 
> 好像是软件库里没有 docker 这个依赖。

可能需要等一段时间。前段时间 Mini 项目的 Docker 软件包编译也出了点问题，应该很快就能好。
或者你说一下你的设备我手动触发下编译。

**Comment by xuanshaowl** [comment]
X86 64

**Comment by fucktimi** [comment]
我的也是x86 64，

**Comment by fucktimi** [comment]
> > 提示如下：
> > Unknown package 'luci-app-dockerman'. Collected errors:
> > 
> > * pkg_hash_check_unresolved: cannot find dependency docker for luci-app-dockerman
> > * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-dockerman found, but incompatible with the architectures configured
> > * opkg_install_cmd: Cannot install package luci-app-dockerman.
> > 
> > 好像是软件库里没有 docker 这个依赖。
> 
> 可能需要等一段时间。前段时间 Mini 项目的 Docker 软件包编译也出了点问题，应该很快就能好。 或者你说一下你的设备我手动触发下编译。

我的是x86，j4125
