### ISSUE TITLE
朋友，下载地址打不开了

### ISSUE THREAD

**Issue by xcdahai** [SuLingGG/OpenWrt-Mini#5]

**Comment by xcdahai** [comment]
X86_64的

**Comment by SuLingGG** [comment]
@xcdahai 由于 IDC 商维护，OpenWrt.cc 服务器网络中断约 24 小时，现已恢复。

**Comment by xcdahai** [comment]
> @xcdahai Idc 的白痴， OpenWrt.cc 的 24 个， OpenWrt.cc 的， OpenWrt.cc 的。

大神，反馈一个问题，编译自带的turbo acc加速默认开启，BT下载CPU占用100%，关闭加速后占用不到20%。

**Comment by bmyjacks** [comment]
现在又是502?

**Comment by SuLingGG** [comment]
@bmyjacks 依旧是 IDC 那边在维护。

**Comment by SuLingGG** [comment]
> > @xcdahai Idc 的白痴， OpenWrt.cc 的 24 个， OpenWrt.cc 的， OpenWrt.cc 的。
> 
> 大神，反馈一个问题，编译自带的turbo acc加速默认开启，BT下载CPU占用100%，关闭加速后占用不到20%。

那就别用了...这个功能可能在不同设备上表现也不一样...😂😂
