### ISSUE TITLE
无法安装passwall

### ISSUE THREAD

**Issue by bmyjacks** [SuLingGG/OpenWrt-Mini#6]
在最新的4-14版本中，nanopi-r4s-ext4镜像刷写后无法下载passwall。
![image](https://user-images.githubusercontent.com/38985658/114792295-aef98c80-9dba-11eb-8b75-94765a4ef77d.png)

**Comment by SuLingGG** [comment]
可能是因为有关科学上网的某些关键的包编译失败了，可以后天再试试看。

**Comment by SyllableSpec** [comment]
> 可能是因为有关科学上网的某些关键的包编译失败了，可以后天再试试看。

R4S 16号没更新嘛～

**Comment by SuLingGG** [comment]
> R4S 16 号没更新嘛～

前几天编译遇到了一些问题，微调流程后已经恢复编译了，R4S 的固件已经恢复，可以下载最新固件或者 opkg update 然后安装你想要的软件包试试。

**Comment by SuLingGG** [comment]
> 在最新的 4-14 版本中，nanopi-r4s-ext4 镜像刷写后无法下载 passwall。
> ![image](https://user-images.githubusercontent.com/38985658/114792295-aef98c80-9dba-11eb-8b75-94765a4ef77d.png)

已修复。

**Comment by bmyjacks** [comment]
![image](https://user-images.githubusercontent.com/38985658/116753556-d6e32400-aa39-11eb-92a3-2d00aad2a7e9.png)
again

**Comment by Nlqqer** [comment]
@bmyjacks 你这个是哪个版本的？

**Comment by bmyjacks** [comment]
> @bmyjacks 你这个是哪个版本的？

4-30

**Comment by Nlqqer** [comment]
@bmyjacks 用个旧版吧，估计这个包某个依赖编译错了
