### ISSUE TITLE
r4s安装luci-app-qbittorrent，luci-app-kodexplorer 时报错，提示与配置架构不兼容

### ISSUE THREAD

**Issue by aenron** [SuLingGG/OpenWrt-Mini#7]

**Comment by SuLingGG** [comment]
这是上游的问题，其实并不是架构不兼容，是因为它们依赖的一些包编译失败了，而你在安装这些包时因为缺少依赖所以会报错。
“架构不兼容”这个错误其实是 opkg 的 Bug，不管 opkg 在安装过程中遇到了什么错误它都会抛出这个错误，目前暂时无解。
这些包应该都有 Docker 镜像，如果确实要用到的话建议用 Docker 跑。

**Comment by aenron** [comment]
好的，我用其他的代替吧，谢谢。
